# Generated by Django 5.0 on 2024-01-13 23:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutioncenterApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_task_file', models.FileField(blank=True, null=True, upload_to='submitted_tasks/')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutioncenterApp.task')),
                ('user_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TutioncenterApp.usermembers')),
            ],
        ),
    ]
