# Generated by Django 5.0 on 2024-01-14 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutioncenterApp', '0003_alter_tasksubmission_submitted_task_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubmission',
            name='submitted_task_file',
            field=models.FileField(blank=True, null=True, upload_to='submitted_tasks/'),
        ),
    ]
